# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratice', '0002_auto_20170603_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
